# Form implementation generated from reading ui file '.\app.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 651)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cameraFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.cameraFrame.setGeometry(QtCore.QRect(10, 10, 480, 340))
        self.cameraFrame.setMinimumSize(QtCore.QSize(480, 340))
        self.cameraFrame.setMaximumSize(QtCore.QSize(480, 340))
        self.cameraFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.cameraFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.cameraFrame.setObjectName("cameraFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.cameraFrame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.cameraLabel = QtWidgets.QLabel(parent=self.cameraFrame)
        self.cameraLabel.setScaledContents(True)
        self.cameraLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.cameraLabel.setObjectName("cameraLabel")
        self.gridLayout.addWidget(self.cameraLabel, 0, 0, 1, 1)
        self.optionsFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.optionsFrame.setGeometry(QtCore.QRect(490, 10, 290, 340))
        self.optionsFrame.setMinimumSize(QtCore.QSize(290, 340))
        self.optionsFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.optionsFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.optionsFrame.setObjectName("optionsFrame")
        self.drawOptionsGroupbox = QtWidgets.QGroupBox(parent=self.optionsFrame)
        self.drawOptionsGroupbox.setGeometry(QtCore.QRect(10, 70, 82, 141))
        self.drawOptionsGroupbox.setMinimumSize(QtCore.QSize(82, 111))
        self.drawOptionsGroupbox.setObjectName("drawOptionsGroupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.drawOptionsGroupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.facesCheckbox = QtWidgets.QCheckBox(parent=self.drawOptionsGroupbox)
        self.facesCheckbox.setObjectName("facesCheckbox")
        self.verticalLayout.addWidget(self.facesCheckbox)
        self.ageCheckbox = QtWidgets.QCheckBox(parent=self.drawOptionsGroupbox)
        self.ageCheckbox.setObjectName("ageCheckbox")
        self.verticalLayout.addWidget(self.ageCheckbox)
        self.genderCheckbox = QtWidgets.QCheckBox(parent=self.drawOptionsGroupbox)
        self.genderCheckbox.setObjectName("genderCheckbox")
        self.verticalLayout.addWidget(self.genderCheckbox)
        self.toggleDrawButton = QtWidgets.QPushButton(parent=self.drawOptionsGroupbox)
        self.toggleDrawButton.setObjectName("toggleDrawButton")
        self.verticalLayout.addWidget(self.toggleDrawButton)
        self.gatherGroupbox = QtWidgets.QGroupBox(parent=self.optionsFrame)
        self.gatherGroupbox.setGeometry(QtCore.QRect(100, 70, 181, 141))
        self.gatherGroupbox.setMinimumSize(QtCore.QSize(121, 111))
        self.gatherGroupbox.setObjectName("gatherGroupbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gatherGroupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.timeLayout = QtWidgets.QHBoxLayout()
        self.timeLayout.setObjectName("timeLayout")
        self.perSecLabel = QtWidgets.QLabel(parent=self.gatherGroupbox)
        self.perSecLabel.setMaximumSize(QtCore.QSize(50, 16777215))
        self.perSecLabel.setObjectName("perSecLabel")
        self.timeLayout.addWidget(self.perSecLabel)
        self.timeSpinbox = QtWidgets.QSpinBox(parent=self.gatherGroupbox)
        self.timeSpinbox.setMinimumSize(QtCore.QSize(0, 30))
        self.timeSpinbox.setMinimum(1)
        self.timeSpinbox.setMaximum(999)
        self.timeSpinbox.setProperty("value", 3)
        self.timeSpinbox.setObjectName("timeSpinbox")
        self.timeLayout.addWidget(self.timeSpinbox)
        self.verticalLayout_2.addLayout(self.timeLayout)
        self.startButton = QtWidgets.QPushButton(parent=self.gatherGroupbox)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_2.addWidget(self.startButton)
        self.gatherStatusLabel = QtWidgets.QLabel(parent=self.gatherGroupbox)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.gatherStatusLabel.setFont(font)
        self.gatherStatusLabel.setStyleSheet("background: #f0ad4e;")
        self.gatherStatusLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.gatherStatusLabel.setObjectName("gatherStatusLabel")
        self.verticalLayout_2.addWidget(self.gatherStatusLabel)
        self.layoutWidget = QtWidgets.QWidget(parent=self.optionsFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 203, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.camerasLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.camerasLayout.setContentsMargins(0, 0, 0, 0)
        self.camerasLayout.setObjectName("camerasLayout")
        self.camerasLabel = QtWidgets.QLabel(parent=self.layoutWidget)
        self.camerasLabel.setObjectName("camerasLabel")
        self.camerasLayout.addWidget(self.camerasLabel)
        self.camerasCombobox = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.camerasCombobox.setObjectName("camerasCombobox")
        self.camerasLayout.addWidget(self.camerasCombobox)
        self.toggleCameraButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.toggleCameraButton.setObjectName("toggleCameraButton")
        self.camerasLayout.addWidget(self.toggleCameraButton)
        self.dataFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.dataFrame.setGeometry(QtCore.QRect(10, 350, 480, 260))
        self.dataFrame.setMinimumSize(QtCore.QSize(480, 260))
        self.dataFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dataFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dataFrame.setObjectName("dataFrame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.dataFrame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.table = QtWidgets.QTableWidget(parent=self.dataFrame)
        self.table.setObjectName("table")
        self.table.setColumnCount(5)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        self.table.horizontalHeader().setDefaultSectionSize(90)
        self.table.horizontalHeader().setSortIndicatorShown(False)
        self.table.horizontalHeader().setStretchLastSection(False)
        self.table.verticalHeader().setCascadingSectionResizes(False)
        self.gridLayout_2.addWidget(self.table, 0, 0, 1, 1)
        self.exportFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.exportFrame.setGeometry(QtCore.QRect(490, 350, 290, 261))
        self.exportFrame.setMinimumSize(QtCore.QSize(290, 260))
        self.exportFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.exportFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.exportFrame.setObjectName("exportFrame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.exportFrame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dataGroupbox = QtWidgets.QGroupBox(parent=self.exportFrame)
        self.dataGroupbox.setMinimumSize(QtCore.QSize(121, 241))
        self.dataGroupbox.setMaximumSize(QtCore.QSize(121, 241))
        self.dataGroupbox.setObjectName("dataGroupbox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dataGroupbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.reloadButton = QtWidgets.QPushButton(parent=self.dataGroupbox)
        self.reloadButton.setObjectName("reloadButton")
        self.verticalLayout_3.addWidget(self.reloadButton)
        self.clearButton = QtWidgets.QPushButton(parent=self.dataGroupbox)
        self.clearButton.setObjectName("clearButton")
        self.verticalLayout_3.addWidget(self.clearButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.deleteDBButton = QtWidgets.QPushButton(parent=self.dataGroupbox)
        self.deleteDBButton.setMinimumSize(QtCore.QSize(101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        self.deleteDBButton.setFont(font)
        self.deleteDBButton.setStyleSheet("QPushButton#deleteDBButton{\n"
"    background: rgba(217, 83, 79, 1);\n"
"    color: #f7f7f7;\n"
"    border: 2px solid rgba(217, 83, 79, 1);\n"
"    border-radius: 7px;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"QPushButton#deleteDBButton:hover{\n"
"    background: rgba(217, 83, 79, 0.65);\n"
"}\n"
"\n"
"QPushButton#deleteDBButton:pressed{\n"
"    background: rgba(217, 83, 79, 0.85);\n"
"}")
        self.deleteDBButton.setAutoRepeat(False)
        self.deleteDBButton.setAutoExclusive(False)
        self.deleteDBButton.setFlat(False)
        self.deleteDBButton.setObjectName("deleteDBButton")
        self.verticalLayout_3.addWidget(self.deleteDBButton)
        self.gridLayout_3.addWidget(self.dataGroupbox, 0, 0, 1, 1)
        self.exportGroupbox = QtWidgets.QGroupBox(parent=self.exportFrame)
        self.exportGroupbox.setMinimumSize(QtCore.QSize(141, 241))
        self.exportGroupbox.setObjectName("exportGroupbox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.exportGroupbox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.exportAsLabel = QtWidgets.QLabel(parent=self.exportGroupbox)
        font = QtGui.QFont()
        font.setBold(True)
        self.exportAsLabel.setFont(font)
        self.exportAsLabel.setObjectName("exportAsLabel")
        self.verticalLayout_4.addWidget(self.exportAsLabel)
        self.exportButtonLayout = QtWidgets.QVBoxLayout()
        self.exportButtonLayout.setSpacing(4)
        self.exportButtonLayout.setObjectName("exportButtonLayout")
        self.exportExcelButton = QtWidgets.QPushButton(parent=self.exportGroupbox)
        self.exportExcelButton.setMinimumSize(QtCore.QSize(121, 31))
        self.exportExcelButton.setStyleSheet("QPushButton#exportExcelButton{\n"
"    background: rgba(29, 111, 66, 1);\n"
"    border: 2px solid rgba(29, 111, 66, 1);\n"
"    border-radius: 7px;\n"
"    color: #f7f7f7;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"QPushButton#exportExcelButton:hover{\n"
"    background: rgba(29, 111, 66, 0.65);\n"
"}\n"
"\n"
"QPushButton#exportExcelButton:pressed{\n"
"    background: rgba(29, 111, 66, 0.85);\n"
"}")
        self.exportExcelButton.setObjectName("exportExcelButton")
        self.exportButtonLayout.addWidget(self.exportExcelButton)
        self.exportSqlButton = QtWidgets.QPushButton(parent=self.exportGroupbox)
        self.exportSqlButton.setMinimumSize(QtCore.QSize(121, 31))
        self.exportSqlButton.setStyleSheet("QPushButton#exportSqlButton{\n"
"    background: rgba(91, 192, 222, 1);\n"
"    border: 2px solid rgba(91, 192, 222, 1);\n"
"    border-radius: 7px;\n"
"    color: #f7f7f7;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"QPushButton#exportSqlButton:hover{\n"
"    background: rgba(91, 192, 222, 0.65);\n"
"}\n"
"\n"
"QPushButton#exportSqlButton:pressed{\n"
"    background: rgba(91, 192, 222, 0.85);\n"
"}")
        self.exportSqlButton.setObjectName("exportSqlButton")
        self.exportButtonLayout.addWidget(self.exportSqlButton)
        self.exportCsvButton = QtWidgets.QPushButton(parent=self.exportGroupbox)
        self.exportCsvButton.setMinimumSize(QtCore.QSize(121, 31))
        self.exportCsvButton.setStyleSheet("QPushButton#exportCsvButton{\n"
"    background: rgba(2, 117, 216, 1);\n"
"    border: 2px solid rgba(2, 117, 216, 1);\n"
"    border-radius: 7px;\n"
"    color: #f7f7f7;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"QPushButton#exportCsvButton:hover{\n"
"    background: rgba(2, 117, 216, 0.65);\n"
"}\n"
"\n"
"QPushButton#exportCsvButton:pressed{\n"
"    background: rgba(2, 117, 216, 0.85);\n"
"}")
        self.exportCsvButton.setObjectName("exportCsvButton")
        self.exportButtonLayout.addWidget(self.exportCsvButton)
        self.exportJsonButton = QtWidgets.QPushButton(parent=self.exportGroupbox)
        self.exportJsonButton.setMinimumSize(QtCore.QSize(121, 31))
        self.exportJsonButton.setStyleSheet("QPushButton#exportJsonButton{\n"
"    background: rgba(255, 193, 7, 1);\n"
"    border: 2px solid rgba(255, 193, 7, 1);\n"
"    border-radius: 7px;\n"
"    color: #f7f7f7;\n"
"    font-weight: 700;\n"
"}\n"
"\n"
"QPushButton#exportJsonButton:hover{\n"
"    background: rgba(255, 193, 7, 0.65);\n"
"}\n"
"\n"
"QPushButton#exportJsonButton:pressed{\n"
"    background: rgba(255, 193, 7, 0.85);\n"
"}")
        self.exportJsonButton.setObjectName("exportJsonButton")
        self.exportButtonLayout.addWidget(self.exportJsonButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.exportButtonLayout.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.exportButtonLayout)
        self.gridLayout_3.addWidget(self.exportGroupbox, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Age & Gender Detection"))
        self.cameraLabel.setText(_translate("MainWindow", "CAM 0"))
        self.drawOptionsGroupbox.setTitle(_translate("MainWindow", "Draw"))
        self.facesCheckbox.setText(_translate("MainWindow", "Faces"))
        self.ageCheckbox.setText(_translate("MainWindow", "Age"))
        self.genderCheckbox.setText(_translate("MainWindow", "Gender"))
        self.toggleDrawButton.setText(_translate("MainWindow", "Toggle"))
        self.gatherGroupbox.setTitle(_translate("MainWindow", "Gather"))
        self.perSecLabel.setText(_translate("MainWindow", "Per sec."))
        self.timeSpinbox.setSuffix(_translate("MainWindow", "s"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.gatherStatusLabel.setText(_translate("MainWindow", "Stopped"))
        self.camerasLabel.setText(_translate("MainWindow", "Cameras"))
        self.toggleCameraButton.setText(_translate("MainWindow", "Toggle"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "#"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Age"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Datetime"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cam"))
        self.dataGroupbox.setTitle(_translate("MainWindow", "Data"))
        self.reloadButton.setText(_translate("MainWindow", "Reload"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.deleteDBButton.setText(_translate("MainWindow", "Delete Database"))
        self.exportGroupbox.setTitle(_translate("MainWindow", "Export"))
        self.exportAsLabel.setText(_translate("MainWindow", "Export as"))
        self.exportExcelButton.setText(_translate("MainWindow", "Excel"))
        self.exportSqlButton.setText(_translate("MainWindow", "Sql"))
        self.exportCsvButton.setText(_translate("MainWindow", "Csv"))
        self.exportJsonButton.setText(_translate("MainWindow", "Json"))
